#!/bin/bash
echo "# Deleting old file..."
rm ./check_empty.exe
echo "# Building new file..."
g++ check_empty.cpp -o check_empty.exe -std=c++11 -lz3
echo "# Checking emptiness..."
echo "--------------------"
./check_empty.exe $1 $2
