#!/bin/bash
echo "# Deleting old file..."
rm ./compiled/empty.exe
echo "# Building new file..."
g++ empty.cpp -o compiled/empty.exe -std=c++11 -lz3
echo "# Checking emptiness..."
echo "--------------------"
./compiled/empty.exe $1 $2 $3 $4 $5
