#!/bin/bash
echo "# Deleting old file..."
rm ./compiled/test.exe
echo "# Building new file..."
g++ test.cpp -o compiled/test.exe -std=c++11 -lz3
echo "# Running test..."
echo "--------------------"
./compiled/test.exe
